---
title: "Draft Quarto document"
author: "Conchita Fraguas"
format: html
---

## Testing formatting styles

```{r setup}
library(tidyverse)
library(targets)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Making a table

```{r}
lipidomics |>
  group_by(metabolite) |>
  summarise(across(value, list(mean = mean, sd = sd))) |>
  mutate(across(where(is.numeric), \(x) round(x, digits = 2))) |>
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
  select(Metabolite = metabolite, "Mean SD" = "MeanSD")
```

## Results : basic stats table

```{r}
tar_read(table_descriptive_stats) |>
  knitr::kable(
    caption = "The mean and SD of metabolites in the lipidomics dataset"
  )
```

## Results: Distribution plot

```{r}
print(tar_read(plot_distributions))
```

## Preparing the data

```{r}
lipidomics |>
  count(code, metabolite) |>
  filter(n > 1)
```

## Cleaning/pre-processing data

```{r}
clean(lipidomics)
```

```{r}
preprocessing(lipidomics)
```

```{r}
just_cholesterol <- lipidomics |>
  filter(metabolite == "Cholesterol") |>
  preprocessing()
```

```{r}
glm(
  formula = class ~ value,
  data = just_cholesterol,
  family = binomial
) |>
  broom::tidy(exponentiate = TRUE) |>
  mutate(
    metabolite = unique(just_cholesterol$metabolite),
    model = format(class ~ value),
    .before = everything()
  )
```

```{r}
#' Fitting model
#'
#' @param data 
#' @param model 
#'
#' @returns fitting model

fit_model <- function(data,model) {
  data |>
    stats::glm(model, data = data, family = binomial) |>
    broom::tidy(exponentiate = TRUE) |>
  dplyr::mutate(metabolite = unique(data$metabolite),
   model = format(model),
    .before = everything()
  ) 
}
```
